Important Links:
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
Dataset used in this tutorial:https://archive.ics.uci.edu/ml/datasets/combined+cycle+power+plant

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Import Dataset

In [3]:
ccpp_df = pd.read_excel("CCPP.xlsx")
ccpp_df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

# Define X and Y

In [6]:
x = ccpp_df.drop(["PE"],axis=1).values
y = ccpp_df["PE"].values

print(x,y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] [463.26 444.37 488.56 ... 429.57 435.74 453.28]


# Split Dataset in Train set and Test Set

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)


# Train the model on Train Set

In [8]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(x_train,y_train)

LinearRegression()

# Predict the Test set result

In [12]:
y_predict = reg.predict(x_test)
y_predict

#reg.predict([[14.96,41.76,1024.07,73.17]])

array([431.40245096, 458.61474119, 462.81967423, ..., 432.47380825,
       436.16417243, 439.00714594])

# Evaluate The Model

In [13]:
from sklearn.metrics import r2_score

r2_score(y_test,y_predict)

0.9304112159477682

# Plot the model

# Predicted Values